import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = join(process.cwd(), 'skills')

describe('packaged M3 Skills', () => {
  it('publishes the PubMed helper protocol and failure boundary', () => {
    const content = readFileSync(join(root, 'pubmed-search', 'SKILL.md'), 'utf8')
    expect(content).not.toContain('M0 stub')
    expect(content).toContain('retmax` to `20`')
    expect(content).toContain('more than 200 PMIDs is sent by POST')
    expect(content).toContain('Do not create a Research Import Draft')
    expect(content).toContain('do not invent')
    expect(content).toContain('relative resource `helper.mjs`')
    expect(content).toContain('standard input')
    expect(content).toContain('Do not search')
    expect(content).not.toContain('<packaged-pubmed-skill>')
    expect(content).not.toContain('request.json')
  })

  it('publishes the Draft, one-step expansion, progressive research, and critique boundaries', () => {
    const content = readFileSync(join(root, 'scifork-research', 'SKILL.md'), 'utf8')
    expect(content).not.toContain('M0 stub')
    expect(content).toContain('ResearchImportDraft')
    expect(content).toContain('PMID_DOI_CONSISTENCY_UNVERIFIED')
    expect(content).toContain('Research Expansion Step')
    expect(content).toContain('Research & Expand')
    expect(content).toContain('Progressive Research Run')
    expect(content).toContain('Critique')
    expect(content).toContain('Do not promote a')
    expect(content).toContain('actual retrieval or PDF results')
    expect(content).toContain('do not produce a Draft')
    expect(content).not.toContain('Simulate & Save')
    expect(content).toContain('zero to five')
    expect(content).toContain('confidence: low')
    expect(content).toContain('incoming')
    expect(content).toContain('outgoing')
    expect(content).toContain('Focus remains unchanged')
    expect(content).toContain('explicit user request')
    expect(content).toContain('frontier')
    expect(content).toContain('visited')
    expect(content).toContain('pubmed-search')
    expect(content).toContain('search')
    expect(content).toContain('lookup')
    expect(content).toContain('create_node')
    expect(content).toContain('create_edge')
    expect(content).toContain('delete_edge')
    expect(content).toContain('delete_node')
    expect(content).toContain('delete Edges before Nodes')
    expect(content).toContain('clear or move Focus')
    expect(content).toContain('Do not recurse')
    expect(content).toContain('no new explicit scientific relationship')
    expect(content).toContain('Do not continue in the background')
  })
})
