import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = join(process.cwd(), 'skills')

describe('packaged M3 Skills', () => {
  it('publishes the PubMed helper protocol and failure boundary', () => {
    const content = readFileSync(join(root, 'pubmed-search', 'SKILL.md'), 'utf8')
    expect(content).not.toContain('M0 stub')
    expect(content).toContain('retmax` to `20`')
    expect(content).toContain('more than 200 PMIDs is sent by POST')
    expect(content).toContain('Do not create a Research Import Draft')
    expect(content).toContain('do not invent')
    expect(content).toContain('relative resource `helper.mjs`')
    expect(content).toContain('standard input')
    expect(content).toContain('Do not search')
    expect(content).toContain('optional abstract')
    expect(content).toContain('DSH Chat may retain')
    expect(content).toContain('SciFork cannot delete')
    expect(content).not.toContain('<packaged-pubmed-skill>')
    expect(content).not.toContain('request.json')
  })

  it('publishes the Draft, one-step expansion, progressive research, and critique boundaries', () => {
    const content = readFileSync(join(root, 'scifork-research', 'SKILL.md'), 'utf8')
    expect(content).not.toContain('M0 stub')
    expect(content).toContain('ResearchImportDraft')
    expect(content).toContain('PMID_DOI_CONSISTENCY_UNVERIFIED')
    expect(content).toContain('Research Expansion Step')
    expect(content).toContain('Research & Expand')
    expect(content).toContain('Progressive Research Run')
    expect(content).toContain('深度研究')
    expect(content).toContain('深度调研')
    expect(content).toContain('not an Evidence-only enrichment request')
    expect(content).toContain('at least two levels')
    expect(content).toContain('exactly one new Hypothesis')
    expect(content).toContain('terminal side branches')
    expect(content.replace(/\s+/g, ' ')).toContain('Predictions are always terminal')
    expect(content).toContain('Critique')
    expect(content).toContain('Do not promote a')
    expect(content).toContain('actual retrieval or PDF results')
    expect(content).toContain('do not produce a Draft')
    expect(content).not.toContain('Simulate & Save')
    expect(content).toContain('zero to five')
    expect(content).toContain('confidence: low')
    expect(content).toContain('incoming')
    expect(content).toContain('outgoing')
    expect(content).toContain('Focus remains unchanged')
    expect(content).toContain('explicit user request')
    expect(content).toContain('current continuation')
    expect(content).toContain('visited')
    expect(content).toContain('pubmed-search')
    expect(content).toContain('search')
    expect(content).toContain('lookup')
    expect(content).toContain('create_node')
    expect(content).toContain('create_edge')
    expect(content.toLowerCase()).toContain('from the existing anchor to the new node')
    expect(content).toContain('create_question')
    expect(content).toContain('create_framing_link')
    expect(content).toContain('create_evidence_assertion')
    expect(content).toContain('machine_reviewed')
    expect(content).toContain('Citation Snapshot')
    expect(content).toContain('title-only')
    expect(content).toContain('human \`reviewed\`')
    expect(content).toContain('delete_framing_link')
    expect(content).toContain('Never persist authors')
    expect(content).toContain('abstract bodies')
    expect(content).toContain('DSH Chat')
    expect(content).toContain('publicationRefs')
    expect(content).toContain('structured')
    expect(content).toContain('scientific Edge to a Question')
    expect(content).toContain('Review an Evidence Assertion')
    expect(content).toContain('delete_edge')
    expect(content).toContain('delete_node')
    expect(content).toContain('delete Framing Links')
    expect(content).toContain('before Nodes')
    expect(content).toContain('Initial question intake')
    expect(content.toLowerCase()).toContain('after the user message is submitted')
    const normalized = content.replace(/[`]/g, '').replace(/\s+/g, ' ')
    expect(normalized).toContain('create_question before retrieval')
    expect(normalized).toContain('create machine-reviewed Evidence before creating')
    expect(content).toContain('clear or move Focus')
    expect(content).toContain('current`, `selected`, or `focused`')
    expect(content).toContain('operation: focus')
    expect(content).toContain('Never infer an id from a visible label')
    expect(content.replace(/\s+/g, ' ')).toContain('Do not recurse')
    expect(content).toContain('no new explicit scientific relationship')
    expect(content).toContain('Do not continue in the background')
    expect(content).toContain('first non-empty Markdown paragraph')
    expect(content).toContain('bold summary sentence')
    expect(content).toContain('Do not put Evidence Assertion')
  })
})
